"use client";

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import Calendar from "../components/Calendar";
import { useEffect, useState } from "react";
import { type DateType } from "@types";
import Spinner from "~/components/Spinner";
import Menu from "~/components/Menu";

const Home: NextPage = () => {
  const [date, setDate] = useState<DateType>({
    justDate: null,
    dateTime: null,
  });

  useEffect(() => {
    console.log(date.dateTime);
    if (date.dateTime) {
      checkMenuStatus();
    }
  }, [date]);

  // tRPC
  const { mutate: checkMenuStatus, isSuccess } =
    api.menu.checkMenuStatus.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {!date.dateTime && <Calendar date={date} setDate={setDate} />}
        {date.dateTime && isSuccess ? (
          <Menu />
        ) : (
          <div className="flex h-screen items-center justify-center">
            <Spinner />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
