"use client";

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import Calendar from "../components/Calendar";
import { useState } from "react";
import { type DateType } from "@types";

const Home: NextPage = () => {
  const [date, setDate] = useState<DateType>({
    justDate: null,
    dateTime: null,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Calendar date={date} setDate={setDate} />
    </>
  );
};

export default Home;
